// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaDVQ1xhpexJw1OFpn-1tG129p3tRrpUA',
    appId: '1:528720101330:web:19e2b8d1e0a4341d2ed20b',
    messagingSenderId: '528720101330',
    projectId: 'berrymaster-c0093',
    authDomain: 'berrymaster-c0093.firebaseapp.com',
    databaseURL: 'https://berrymaster-c0093-default-rtdb.firebaseio.com',
    storageBucket: 'berrymaster-c0093.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIxI_VHrNKpzKrbgF4WL6kaNf35ahs8PM',
    appId: '1:528720101330:android:0776c331ca69340d2ed20b',
    messagingSenderId: '528720101330',
    projectId: 'berrymaster-c0093',
    databaseURL: 'https://berrymaster-c0093-default-rtdb.firebaseio.com',
    storageBucket: 'berrymaster-c0093.appspot.com',
  );
}
